name: pomodoro_elite
description: "Odaklanmayı ve verimliliği artıran profesyonel Pomodoro uygulaması."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  audioplayers: ^6.5.1
  confetti: ^0.8.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  fl_chart: ^0.68.0
  google_mobile_ads: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/music/
    - assets/sounds/bell/
    - assets/translations/
    - assets/icon/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

# --- İKON VE SPLASH AYARLARI ---
# --- 1. UYGULAMA İKONU (Ana Ekrandaki) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Yeni logonun yolunu gösteriyoruz:
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  # İkonun arkası Siyah olsun (Senin logonun arkası şeffafsa bu renk görünür)
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/icon.png"

# --- 2. SPLASH EKRANI (Açılış) ---
flutter_native_splash:
  # Arka plan Siyah
  color: "#121212"

